language: perl
perl:
   - "5.16"
   - "5.14"
   - "5.12"
   - "5.10"

before_install:
   # Prevent any test problems with this file
   - rm .travis.yml
install:
   - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
   - cpanm --installdeps --notest --skip-satisfied .

# whitelist
branches:
   only:
     - /^build\/.*/

