language: perl
perl:
   - "5.16"
   - "5.14"
   - "5.12"
   - "5.10"

before_install:
   # Prevent any test problems with this file
   - rm .travis.yml
# Travis-CI defaults should be enough

# whitelist
branches:
   only:
     - /^build\/.*/

