---
abstract: 'C-like data types for Moo'
author:
  - 'Brendan Byrd <BBYRD@CPAN.org>'
build_requires:
  Moo: 0.009001
  Test::CheckDeps: 0.002
  Test::Exception: 0.27
  Test::UseAllModules: 0.10
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300027, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooX-Types-CLike
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
provides:
  MooX::Types::CLike:
    file: lib/MooX/Types/CLike.pm
    version: 0.95_004
requires:
  Data::Float: 0.008
  MooX::Types::MooseLike: 0.06
  perl: v5.10.1
  sanity: 0.91
resources:
  X_irc: irc://irc.perl.org/#web-simple
  bugtracker: https://github.com/SineSwiper/MooX-Types-CLike/issues
  homepage: https://github.com/SineSwiper/MooX-Types-CLike/wiki
  repository: git://github.com/SineSwiper/MooX-Types-CLike.git
version: 0.95_004
x_Dist_Zilla:
  perl:
    version: 5.016000
  plugins:
    -
      class: Dist::Zilla::Plugin::ReportPhase
      name: '@Author::BBYRD/ReportPhase'
      version: 0.00
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Author::BBYRD/MakeMaker'
      version: 4.300027
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@Author::BBYRD/Git::NextVersion'
      version: 2.001
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      name: '@Author::BBYRD/Git::GatherDir'
      version: 2.001
    -
      class: Dist::Zilla::Plugin::OurPkgVersion
      name: '@Author::BBYRD/OurPkgVersion'
      version: 0.004000
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@Author::BBYRD/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Author::BBYRD/PruneCruft'
      version: 4.300027
    -
      class: Dist::Zilla::Plugin::GitFmtChanges
      name: '@Author::BBYRD/GitFmtChanges'
      version: 0.005
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::BBYRD/ManifestSkip'
      version: 4.300027
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::BBYRD/Manifest'
      version: 4.300027
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::BBYRD/License'
      version: 4.300027
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::BBYRD/ReadmeHtmlInBuild'
      version: 0.120120
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::BBYRD/ReadmePodInBuild'
      version: 0.120120
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: '@Author::BBYRD/InstallGuide'
      version: 1.200000
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Author::BBYRD/ExecDir'
      version: 4.300027
    -
      class: Dist::Zilla::Plugin::Test::Compile
      name: '@Author::BBYRD/Test::Compile'
      version: 1.112820
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Author::BBYRD/PodCoverageTests'
      version: 4.300027
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::BBYRD/PodSyntaxTests'
      version: 4.300027
    -
      class: Dist::Zilla::Plugin::RunExtraTests
      name: '@Author::BBYRD/RunExtraTests'
      version: 0.007
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: '@Author::BBYRD/NoTabsTests'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::Test::EOL
      name: '@Author::BBYRD/Test::EOL'
      version: 0.07
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Meta::JSON
      name: '@Author::BBYRD/Test::CPAN::Meta::JSON'
      version: 0.003
    -
      class: Dist::Zilla::Plugin::Test::CheckDeps
      name: '@Author::BBYRD/Test::CheckDeps'
      version: 0.005
    -
      class: Dist::Zilla::Plugin::Test::Portability
      name: '@Author::BBYRD/Test::Portability'
      version: 2.000003
    -
      class: Dist::Zilla::Plugin::Test::Synopsis
      name: '@Author::BBYRD/Test::Synopsis'
      version: 2.000002
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: '@Author::BBYRD/Test::MinimumVersion'
      version: 2.000002
    -
      class: Dist::Zilla::Plugin::Test::CheckManifest
      name: '@Author::BBYRD/Test::CheckManifest'
      version: 0.04
    -
      class: Dist::Zilla::Plugin::Test::DistManifest
      name: '@Author::BBYRD/Test::DistManifest'
      version: 2.000002
    -
      class: Dist::Zilla::Plugin::Test::UseAllModules
      name: '@Author::BBYRD/Test::UseAllModules'
      version: 0.002
    -
      class: Dist::Zilla::Plugin::Test::Version
      name: '@Author::BBYRD/Test::Version'
      version: 0.002004
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@Author::BBYRD/ReportVersions::Tiny'
      version: 1.08
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Author::BBYRD/@Prereqs/AutoPrereqs'
      version: 4.300027
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@Author::BBYRD/@Prereqs/MinimumPerl'
      version: 1.003
    -
      class: Dist::Zilla::Plugin::MinimumPrereqs
      name: '@Author::BBYRD/@Prereqs/MinimumPrereqs'
      version: 0.92
    -
      class: Dist::Zilla::Plugin::PrereqsClean
      name: '@Author::BBYRD/@Prereqs/PrereqsClean'
      version: 0.92
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: '@Author::BBYRD/CheckPrereqsIndexed'
      version: 0.007
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::BBYRD/MetaConfig'
      version: 4.300027
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::BBYRD/MetaJSON'
      version: 4.300027
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::BBYRD/MetaYAML'
      version: 4.300027
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: '@Author::BBYRD/MetaNoIndex'
      version: 4.300027
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@Author::BBYRD/MetaProvides::Package'
      version: 1.14000001
    -
      class: Dist::Zilla::Plugin::MetaResourcesFromGit
      name: '@Author::BBYRD/MetaResourcesFromGit'
      version: 1.103620
    -
      class: Dist::Zilla::Plugin::CopyFilesFromBuild
      name: '@Author::BBYRD/CopyFilesFromBuild'
      version: 0.103510
    -
      class: Dist::Zilla::Plugin::TravisYML
      name: '@Author::BBYRD/TravisYML'
      version: 0.95
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      name: '@Author::BBYRD/Git::CheckFor::CorrectBranch'
      version: 0.005
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      name: '@Author::BBYRD/Git::CommitBuild'
      version: 2.001
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Author::BBYRD/@Git/Check'
      version: 2.001
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Author::BBYRD/@Git/Commit'
      version: 2.001
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Author::BBYRD/@Git/Tag'
      version: 2.001
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Author::BBYRD/@Git/Push'
      version: 2.001
    -
      class: Dist::Zilla::Plugin::GitHub::Update
      name: '@Author::BBYRD/GitHub::Update'
      version: 0.27
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::BBYRD/TestRelease'
      version: 4.300027
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::BBYRD/ConfirmRelease'
      version: 4.300027
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::BBYRD/UploadToCPAN'
      version: 4.300027
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: '@Author::BBYRD/InstallRelease'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::Clean
      name: '@Author::BBYRD/Clean'
      version: 0.07
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300027
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300027
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300027
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300027
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300027
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300027
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300027
